### ISSUE TITLE
Download links for all versions of UP Studio except for Mac broken

### ISSUE THREAD

**Issue by TheAppleFreak** [up3d-dev/up3d-dev.github.io#1]
It appears that in the last commit (the "remove useless files" commit), almost every version of UP Studio was removed from the downloads directory, breaking all of the download links on your main site. I would suggest possibly reverting the commit so those files become accessible once more.

**Comment by zhangximin** [comment]
I can't keep files larger than 100M at github. While you can access those files from All Versions: http://cn.up3d.com:90/downloads/
